name: Deploy in vps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    environment: Boom
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ secrets.PATH }}
            git pull
            docker restart hunti
